# Generated by Django 3.1.2 on 2020-10-28 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoutput', models.FileField(upload_to='')),
                ('zipfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.uploadfile')),
            ],
        ),
    ]
