# Generated by Django 3.1.2 on 2020-12-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_outputfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='boilerplate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
