# Generated by Django 3.1.2 on 2020-12-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_uploadfile_boilerplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='fileType',
            field=models.CharField(default='text', max_length=6),
        ),
    ]
