# Generated by Django 3.1.2 on 2020-10-26 18:14

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploaded',
            field=models.FileField(upload_to=upload.models.random_filename, verbose_name='uploaded file'),
        ),
    ]
