# Generated by Django 3.1.2 on 2020-10-27 11:40

from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20201026_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploaded',
            field=models.FileField(upload_to=upload.models.random_filename),
        ),
        migrations.CreateModel(
            name='OutputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoutput', models.FileField(upload_to='')),
                ('zipfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.uploadfile')),
            ],
        ),
    ]
