# Generated by Django 3.1.2 on 2020-12-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20201027_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatMapFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmapoutput', models.ImageField(upload_to='')),
                ('zipfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.uploadfile')),
            ],
        ),
    ]
